apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Ensure this matches the label on your backend pods
  ports:
    - protocol: TCP
      port: 4000   # This should match the port your backend is listening on
      targetPort: 4000
  type: ClusterIP
